package com.facebook.messengerclone;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.Shader;
import android.view.View;

final class ThemePreviewView extends View {
    private final String key; private final boolean selected; private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
    ThemePreviewView(Context c,String key,boolean selected){super(c);this.key=key;this.selected=selected;setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
    private int c(String s){return Color.parseColor(s);} private float d(float x){return x*getResources().getDisplayMetrics().density;}
    private int[] bg(){switch(key){case"instagram":return new int[]{c("#000000"),c("#000000")};case"instagram-classic":return new int[]{c("#fff5fb"),c("#eee8ff"),c("#eaf5ff")};case"love":return new int[]{c("#76005f"),c("#27002d")};case"ocean":return new int[]{c("#dff8ff"),c("#d8edf4"),c("#edfaff")};case"sunset":return new int[]{c("#fff3de"),c("#ffe7df"),c("#fff8ec")};case"monochrome":return new int[]{c("#f4f4f4"),c("#dedede")};case"glow-pup":return new int[]{c("#020017"),c("#17105b"),c("#2013aa")};case"odyssey":return new int[]{c("#041d22"),c("#0a3a42"),c("#09262d")};case"supergirl":return new int[]{c("#131313"),c("#2a1813"),c("#4a170f")};case"avatar":return new int[]{c("#102c2d"),c("#25514d"),c("#736f4d")};case"olivia":return new int[]{c("#3d2937"),c("#79556a"),c("#536141")};case"backrooms":return new int[]{c("#403a18"),c("#756b2d"),c("#302c14")};case"deli-boys":return new int[]{c("#171612"),c("#2a271f"),c("#161512")};case"heart-drive":return new int[]{c("#061353"),c("#261271"),c("#080e44")};case"valentines":return new int[]{c("#3d0b70"),c("#13052f")};default:return new int[]{c("#f7f9fc"),c("#eef3fb")};}}
    private int[] accent(){switch(key){case"instagram":return new int[]{c("#5c10ee"),c("#ac00ee")};case"instagram-classic":return new int[]{c("#833ab4"),c("#fd1d1d"),c("#fcb045")};case"love":return new int[]{c("#ff238f"),c("#ff2e70")};case"ocean":return new int[]{c("#0083b0"),c("#00b4db")};case"sunset":return new int[]{c("#ff512f"),c("#f09819")};case"monochrome":return new int[]{c("#111111"),c("#555555")};case"glow-pup":return new int[]{c("#7565ff"),c("#b191ff")};case"odyssey":return new int[]{c("#176c7d"),c("#59a6a8")};case"supergirl":return new int[]{c("#e72f32"),c("#ff9d18")};case"avatar":return new int[]{c("#417c78"),c("#81b7a6")};case"olivia":return new int[]{c("#ff9fbe"),c("#ffb8cd")};case"backrooms":return new int[]{c("#8f7d3a"),c("#d4bd60")};case"deli-boys":return new int[]{c("#f2ddcd"),c("#f7eadf")};case"heart-drive":return new int[]{c("#d9c5ff"),c("#f0e7ff")};case"valentines":return new int[]{c("#a321e6"),c("#dd09c0")};default:return new int[]{c("#0866ff"),c("#0866ff")};}}
    protected void onDraw(Canvas canvas){super.onDraw(canvas);float w=getWidth(),h=getHeight(),r=d(15);RectF all=new RectF(0,0,w,h);int[] b=bg();p.setShader(new LinearGradient(0,0,w,h,b,null,Shader.TileMode.CLAMP));canvas.drawRoundRect(all,r,r,p);p.setShader(null);int[] a=accent();p.setShader(new LinearGradient(w*.35f,h*.55f,w*.95f,h*.8f,a,null,Shader.TileMode.CLAMP));canvas.drawRoundRect(new RectF(w*.28f,h*.66f,w-d(8),h*.66f+d(13)),d(9),d(9),p);p.setShader(null);p.setColor(0xB8FFFFFF);canvas.drawRoundRect(new RectF(d(8),h-d(25),w*.64f,h-d(12)),d(9),d(9),p);if(selected){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(2));p.setColor(c("#8f75ff"));canvas.drawRoundRect(new RectF(d(2),d(2),w-d(2),h-d(2)),r,r,p);p.setStyle(Paint.Style.FILL);p.setColor(c("#7456ff"));canvas.drawCircle(w-d(17),d(17),d(10.5f),p);p.setColor(Color.WHITE);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(2));p.setStrokeCap(Paint.Cap.ROUND);canvas.drawLine(w-d(21),d(17),w-d(18),d(20),p);canvas.drawLine(w-d(18),d(20),w-d(13),d(13),p);p.setStyle(Paint.Style.FILL);}}
}
