plugins { id 'com.android.application' }

android {
    namespace 'com.facebook.messengerclone'
    compileSdk 35

    defaultConfig {
        applicationId 'com.facebook.messengerclone'
        minSdk 24
        targetSdk 35
        versionCode 198
        versionName '1.97-video-proxy-limit-fix'
        buildConfigField 'String', 'BASE_URL', '"https://messengerextra.duckdns.org"'
    }

    buildFeatures { buildConfig true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release { minifyEnabled false }
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'androidx.media3:media3-common:1.4.1'
    implementation 'androidx.media3:media3-effect:1.4.1'
    implementation 'androidx.media3:media3-transformer:1.4.1'
}
