plugins { id 'com.android.application' }

android {
    namespace 'com.facebook.messengerclone'
    compileSdk 35

    defaultConfig {
        applicationId 'com.facebook.messengerclone'
        minSdk 24
        targetSdk 35
        versionCode 175
        versionName '1.74-grouped-media-gallery'
        buildConfigField 'String', 'BASE_URL', '"https://messengerextra.duckdns.org"'
    }

    buildFeatures { buildConfig true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release { minifyEnabled false }
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
